# SPDX-License-Identifier: GPL-2.0

dtb-y += 	kuk-trizeps8-ipant7.dtb \
			kuk-trizeps8mini-ipant7.dtb \
			kuk-trizeps8mini-ipant7_v2.dtb \
			kuk-trizeps8nano-ipant7.dtb \
			kuk-trizeps8-ipant10.dtb \
			kuk-trizeps8mini-ipant10.dtb \
			kuk-trizeps8nano-ipant10.dtb \
			kuk-trizeps8-pconxs-hdmi.dtb \
			kuk-trizeps8-pconxs_v2-hdmi.dtb \
			kuk-trizeps8-pconxs-edt7cap.dtb \
			kuk-trizeps8-pconxs_v2-edt7cap.dtb \
			kuk-trizeps8mini-pconxs-edt7cap.dtb \
			kuk-trizeps8mini-pconxs_v2-edt7cap.dtb \
			kuk-trizeps8nano-pconxs-edt7cap.dtb \
			kuk-trizeps8nano-pconxs_v2-edt7cap.dtb \
			kuk-trizeps8mini-pconxs-edt7res.dtb \
			kuk-trizeps8mini-pconxs_v2-edt7res.dtb \
			kuk-trizeps8-pconxs_v2-atm0700l61ct.dtb \
			kuk-trizeps8mini-pconxs_v2-atm0700l61ct.dtb \
			kuk-trizeps8nano-pconxs_v2-atm0700l61ct.dtb \
			kuk-trizeps8mini-pconxs-p550hvn06.dtb \
			kuk-trizeps8mini-pconxs_v3-am19201080d1tzqw.dtb \
			kuk-myon2-ipanm7.dtb \
			kuk-myon2nano-ipanm7.dtb \
			kuk-myon2-conxm-hdmi.dtb \
			kuk-myon2nano-conxm-hdmi.dtb \
			kuk-sbcsom-atm0700l61ct.dtb \
			kuk-sbcsom-hdmi.dtb \
			guf-tanaro-atm0700l61ct.dtb \
			guf-tanaro-fg0700w0dsswagl1.dtb \


always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
