# SPDX-License-Identifier: GPL-2.0

dtb-y +=		kuk-trizeps8mini-ipant7_v2.dtb \
			kuk-trizeps8mini-ipant7_v2-new.dtb \
			kuk-trizeps8-ipant7.dtb \
			kuk-trizeps8mini-ipant7.dtb \
			kuk-trizeps8nano-ipant7.dtb \
			kuk-myon2-conxm-hdmi.dtb \
			kuk-trizeps8mini-pconxs-edt7cap.dtb \
			kuk-trizeps8mini-ipant10.dtb \
			kuk-trizeps8mini-pconxs_v3-am19201080d1tzqw.dtb \
			kuk-trizeps8mini-pconxs_v3-scf1001-sistouch.dtb \
			kuk-trizeps8mini-pconxs_v2-edt7cap.dtb \
			kuk-sbcsom-hdmi.dtb \
			kuk-sbcsom-atm0700l61ct.dtb \
			kuk-myon2-ipanm7.dtb \
			kuk-myon2-ipanm7-ov5645.dtb \
			kuk-trizeps8mini-pconxs_v3-atm0700.dtb \
			kuk-trizeps8mini-sharpfin.dtb \
			kuk-trizeps8plus-pconxs2-atm0700l61ct.dtb \
			kuk-trizeps8plus-pconxs2-atm0700l61ct-usdhc100.dtb \
			kuk-trizeps8plus-pconxs2-atm0700l61ct-gpu.dtb \
			kuk-trizeps8plus-pconxs2-atm0700l61ct-ov5640.dtb \
			kuk-trizeps8plus-pconxs2-atm0700l61ct-gpu-ov5640.dtb \
			kuk-trizeps8plus-pconxs2-hdmi.dtb \
			kuk-trizeps8plus-pconxs2-hdmi-gpu.dtb \
			kuk-trizeps8plus-pconxs2-hdmi-gpu-ov5640.dtb \
			kuk-trizeps8plus-ipant7.dtb \
			kuk-trizeps8plus-ipant7-gpu.dtb \
			kuk-trizeps8plus-ipant7-v2.dtb \
			kuk-trizeps8plus-ipant7-v2-gpu.dtb \
			kuk-trizeps8plus-ipant7-v2-ov5640.dtb \
			kuk-trizeps8plus-ipant7-v2-usdhc100-ov5640.dtb \
			kuk-trizeps8plus-ipant7-v2-usdhc100-gpu-ov5640.dtb \
			kuk-trizeps8plus-pconxs3-scf1001.dtb \
			kuk-trizeps8plus-pconxs3-scf1001-usdhc100.dtb \
			kuk-trizeps8plus-pconxs3-scf1001-gpu.dtb \
			kuk-trizeps8plus-pconxs3-scf1001-usdhc100-gpu.dtb \
			kuk-trizeps8plus-pconxs3-hdmi.dtb \
			kuk-trizeps8plus-pconxs3-hdmi-gpu.dtb \
			kuk-trizeps8plus-pconxs3-atm0700l61ct-ov5640.dtb \
			kuk-trizeps8plus-pconxs3-atm0700.dtb \
			kuk-trizeps8plus-pconxs3-atm0700-gpu.dtb \
			kuk-trizeps8mini-pconxs_v2-edt7cap.dtb \
			kuk-trizeps8mini-pconxs_v2-edt7res.dtb \
			kuk-trizeps8mini-pconxs_v2-atm0700l61ct.dtb \
			voxter.dtb \
			alturos-tr8mini.dtb \


#			kuk-myon2-de4.dtb \
#			kuk-trizeps8-ipant10.dtb \
#			kuk-trizeps8nano-ipant10.dtb \
#			kuk-trizeps8-pconxs-hdmi.dtb \
#			kuk-trizeps8-pconxs_v2-hdmi.dtb \
#			kuk-trizeps8-pconxs_v2-edt7cap.dtb \
#			kuk-trizeps8-pconxs-edt7cap.dtb \
#			kuk-trizeps8mini-pconxs-edt7cap.dtb \
#			kuk-trizeps8nano-pconxs-edt7cap.dtb \
#			kuk-trizeps8nano-pconxs_v2-edt7cap.dtb \
#			kuk-trizeps8mini-pconxs-edt7res.dtb \
#			kuk-trizeps8-pconxs_v2-atm0700l61ct.dtb \
#			kuk-trizeps8nano-pconxs_v2-atm0700l61ct.dtb \
#			kuk-trizeps8mini-pconxs-p550hvn06.dtb \

#			kuk-trizeps8mini-pconxs_v3-atm0700.dtb \
#			kuk-myon2nano-ipanm7.dtb \

#			kuk-myon2nano-conxm-hdmi.dtb \

#			guf-tanaro-atm0700l61ct.dtb \
#			guf-tanaro-fg0700w0dsswagl1.dtb \


always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
