#
#  Makefile for Gasket framework and dependent drivers.
#

obj-$(CONFIG_GOOGLE_EDGE_TPU) += gasket.o
obj-$(CONFIG_GOOGLE_EDGE_TPU) += apex.o

gasket-objs	:= gasket_core.o gasket_ioctl.o gasket_interrupt.o gasket_page_table.o gasket_sysfs.o
apex-objs	:= apex_driver.o
